version: "3.6"

services:
  frontend:
    build: .
    ports:
      - "8000:80" # Lobby server
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
  backend:
    build:
      context: .
      dockerfile: DockerfileBackend
    ports:
      - "8080:8080" # Game server
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
